# Generated by Django 5.1 on 2024-09-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='time',
            new_name='Attended_Time',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='conducted_class_time',
            new_name='conducted_time',
        ),
    ]
