# Generated by Django 5.1.1 on 2024-09-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_attendance_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.FloatField(),
        ),
    ]
