# Generated by Django 5.1 on 2024-09-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_time_attendance_attended_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('session_date', models.DateField()),
                ('duration', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='attendance',
            name='conducted_time',
            field=models.FloatField(),
        ),
    ]
