# Generated by Django 5.1.1 on 2024-09-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_attendance_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='topic',
        ),
        migrations.AddField(
            model_name='attendance',
            name='conducted_class_time',
            field=models.FloatField(default=0),
        ),
    ]
